name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
          cache: gradle

      - name: Make Gradle executable (just in case)
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test --no-daemon