name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 23
          cache: gradle

      - name: Make Gradle executable (just in case)
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean jacocoRootReport --no-daemon

      - name: Generate coverage badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/jacocoRootReport/jacocoRootReport.csv
          generate-branches-badge: false
          fail-if-coverage-less-than: 80

      - name: Commit coverage badge to README
        if: success()
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add .github/badges/jacoco.svg
            git commit -m "Update JaCoCo coverage badge" || echo "No changes to commit"
            git push

